### ISSUE TITLE
Add reference to ARIA Authoring Practices in design section

### ISSUE THREAD

**Issue by yatil** [w3c/wai-design-develop-overview#1]
_From @jongund on May 6, 2018 15:48_

The ARIA Authoring practices should be reference under design resources.

https://www.w3.org/TR/wai-aria-practices/ 

_Copied from original issue: w3c/wai-website#69_

**Comment by yatil** [comment]
Probably to this page: https://github.com/w3c/wai-design-develop-overview

**Comment by slhenry** [comment]
https://github.com/w3c/wai-design-develop-overview/pull/6/files
