### ISSUE TITLE
ES update to Design & Develop Overview

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-design-develop-overview#7]
Hi Carlos @cmuncharaz 

When convenient, please update:
https://www.w3.org/WAI/design-develop/es

The changes are shown in this diff:
https://github.com/w3c/wai-design-develop-overview/pull/6/files

Thanks much!

**Comment by cmuncharaz** [comment]
Done, @slhenry.

Here's the pull request containing the update:
https://github.com/w3c/wai-design-develop-overview/pull/8
